# Generated by Django 5.0.7 on 2024-08-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0002_remove_customuser_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('CREATED', 'Created'), ('DELETED', 'Deleted'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=20),
        ),
    ]
