# Generated by Django 5.0.7 on 2024-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0003_alter_logentry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='jellyfin_api_key',
            field=models.CharField(default='werfgwef', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
