# Generated by Django 5.0.7 on 2024-09-11 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0004_config_jellyfin_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('CREATED', 'Created'), ('DELETED', 'Deleted'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SETUP', 'Setup')], max_length=20),
        ),
    ]
