# Generated by Django 5.0.7 on 2024-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0006_config_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='invite_code2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='invite_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
