# Generated by Django 5.0.7 on 2024-11-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0007_config_invite_code2_alter_config_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='invite_code2',
        ),
    ]
