# Generated by Django 5.0.7 on 2024-11-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0009_alter_logentry_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='app_instance_id',
        ),
    ]
