# Generated by Django 5.0.7 on 2025-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0010_remove_config_app_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='jellyseer_api_key',
            field=models.CharField(blank=True, help_text='API Key for Jellyseer authentication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='jellyseer_url',
            field=models.URLField(blank=True, help_text='URL for Jellyseer instance', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='tmdb_access_token',
            field=models.CharField(blank=True, help_text='TMDB Access Token for API authentication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='tmdb_api_key',
            field=models.CharField(blank=True, help_text='TMDB API Key for API authentication', max_length=255, null=True),
        ),
    ]
