# Generated by Django 5.0.7 on 2025-01-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0012_config_jellyseerr_api_key_config_jellyseerr_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='jellyseer_api_key',
        ),
        migrations.RemoveField(
            model_name='config',
            name='jellyseer_url',
        ),
        migrations.AlterField(
            model_name='config',
            name='jellyseerr_api_key',
            field=models.CharField(blank=True, help_text='API Key for Jellyseerr authentication', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='jellyseerr_url',
            field=models.URLField(blank=True, help_text='URL for Jellyseerr instance', max_length=255, null=True),
        ),
    ]
