# Generated by Django 5.0.7 on 2025-01-14 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0013_remove_config_jellyseer_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jellyfin_log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
