# Generated by Django 5.0.7 on 2025-01-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0014_alter_logentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Company Name', max_length=100)),
                ('from_email', models.EmailField(help_text='Email address that will be used to send emails', max_length=254, verbose_name='From Email')),
                ('site_url', models.URLField(default='http://localhost:8000', help_text='Base URL of your site (e.g., https://example.com)', verbose_name='Site URL')),
                ('support_email', models.EmailField(help_text='Email address for support inquiries', max_length=254, verbose_name='Support Email')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=100)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
