# Generated by Django 5.0.7 on 2025-01-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jellyfin_control', '0015_emailsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='company_name',
        ),
    ]
